services:
  app_blue:
    image: "${BLUE_IMAGE}"
    environment:
      APP_POOL: "blue"
      RELEASE_ID: "${RELEASE_ID_BLUE}"
      PORT: "${APP_INTERNAL_PORT}"
    ports:
      - "${BLUE_PORT}:${APP_INTERNAL_PORT}"

  app_green:
    image: "${GREEN_IMAGE}"
    environment:
      APP_POOL: "green"
      RELEASE_ID: "${RELEASE_ID_GREEN}"
      PORT: "${APP_INTERNAL_PORT}"
    ports:
      - "${GREEN_PORT}:${APP_INTERNAL_PORT}"

  nginx:
    image: "nginx:stable"
    container_name: nginx_blue_green
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro